function T = catalog
%BEND1D.CATALOG Return the complete BEND-1D signal catalog.

persistent signalCatalog

if isempty(signalCatalog)
    % Generate TF001..TF230
    nums = (1:230).';
    newIDs = "TF" + sprintfc('%03d', nums);
    
    % Combine original and new IDs
    ID = [];
    ID = [ID; newIDs];
    
    category1 = [ "Percolation", "Planck", "StickSlip", "RingDown", "DiffusionBand", "Fano", "BouncingBall", ...
        "ImpactSpring", "QuantumBarrier", "AvoidedCrossing", "Morse", "BZPulse", "ActionPotential", "ECGBeat", "VanHove", "MarketCrash"];
    category2 = ["Klatno", "Cantilever", "WaterHammer", "ThermalRunaway", "Diffraction", "Titration", "RabiChirp", "MuscleTwitch", "Platinum5Y", "FlashCrash" ];
    
    category3 = ["NasonPleth","VasospasmTCD", "PVCTrain", "CheyneStokes", "EEGBurstSuppress", "TremorOnset", "ArterialPulse", "EMGRecruitment", ...
        "BearingFault", "GearDefect", "RotorRub", "VortexLockIn", "InternalSolitons", "WhaleClicks", "SonarMultipath", "LightningSferic"];
    
    category4 = ["StampShadeRun","PerforationDrift","StampReflectance","PlateWear", ...
        "TreeRing","IceCore","Seismogram","VolcanicTremor", ...
        "RogueWave","StellarTransitFlare","CyclicVoltammetry","FractureAE", ...
        "Pharmacokinetic","EpidemicSeasonal","PollutionEpisode","Chromatogram"];
    
    category5 = ["ECGBeat","ArterialPulse","EEGSpindle","MassSpectrum", ...
        "NMRMultiplet","XRDPeaks","AFMForceCurve","BatteryDischarge", ...
        "FluorescenceBleach","RadioAstronomyLine","OceanThermocline","WellLog"];
    
    category6 = ["PowerGridFault","GearboxDefect","LidarMultiEcho","RadarMicroDoppler", ...
        "MeltPoolInstability","FiberOTDR","NetworkTrafficBursts","LatencyIncident", ...
        "CacheThrash","TrainingLossSchedule","ExoplanetTransitSpots","PulsarProfile", ...
        "GravitationalWaveChirp","MicrolensingPlanet","SolarFlare","QuasarFlare", ...
        "PromoDemand","ProductLaunch","AdstockCampaign","MarketFlashCrash", ...
        "InventoryStockout","PercussiveAttackDecay","VibratoTone","ChordBeating", ...
        "SpeechFormantTransition","AudioIntro","MilankovitchCycles","TurbiditeSequence", ...
        "CavefishNeuromast","NeuralBurstAdaptation"];
    category7 = ["QuantumRamseyDrift","QuantumLeakageBurst","FusionELMSawtooth", ...
        "TokamakDisruption","CalciumTransientTrain","NanoporeCurrent", ...
        "CopyNumberGenome","SpatialTranscriptScan","SemiconductorMetrology", ...
        "LithographyEdge","ParticlePileup","CryogenicPulse","SpaceWeatherStorm", ...
        "GNSSMultipathSlip","HyperspectralMineral","SideChannelPower", ...
        "SecurityBeacon","GPUThermalThrottle","MoELoadImbalance", ...
        "InferenceQueueCollapse","CuspChirpStep","PeakForest","HiddenNeedle", ...
        "NestedWavePackets","CancellationTrap"];
    category8 = ["DASFiberEvent","PhotoacousticAline","OCTRetinalProfile","UltrasoundCrackEcho",...
        "WearableGaitIMU","EEGSeizureOnset","MRFreeInductionDecay","ATACChromatinAccessibility",...
        "WindTurbineGustControl","EVFastCharge","GridInverterOscillation","SatelliteReactionWheel","MicrofluidicDropletTrain","TerahertzLayerEcho","BridgeStrainEvent","MishMashAlpha","MishMashBeta","DoubletOnCliff","NeedleInChirp","DerivativeZoo","MultiscaleComb","FrequencyCrossing","PhaseResetBurst","LacunaryCascade","SmoothRoughSmooth","PeakOnPeak","FalseFlat","SymmetryBreak","CompressionStorm","GrandMishMash"];
    category9 = ["RiemannShockFan","DispersiveHydraulicJump","XAFSEdge", ...
        "QuantumHallPlateaus","FresnelOccultation","CapnogramBreaths", ...
        "DiffusionMRIIVIM","AuditoryBrainstemResponse","TWaveAlternans", ...
        "TurbulenceIntermittency","StressStrainFracture","NanoindentationPopIn", ...
        "DSCPhaseTransitions","TGADecomposition","VanDerPolRelaxation", ...
        "SeismicDispersiveWave","TertiaryCreepFailure","TransformerInrush", ...
        "MEMSPullInRelease","LorenzWingSwitch","DyadicPhaseTwins", ...
        "BoundaryInteriorTwins","RayleighDoubletLadder", ...
        "EqualEnergyScaleLadder","HolderLadder"];
    
    category10 = ["GWChirpRingdown","FRBScatterTail","PulsarGlitchRecovery","MagnetarBurstStorm","XrayQPODrift", ...
        "QubitRamseyWander","JosephsonPhaseSlips","TokamakELMTrain","SolitonCollision","CriticalSlowing", ...
        "BatteryKnee","FuelCellFloodDry","GNSSMultipathFade","RadarMicroDoppler","MeltPoolSpatter", ...
        "CavitationCollapse","ModeBeatingDecay","ValveChatter","NetworkCongestionBurst","ThermalThrottle", ...
        "CGMMealStack","SleepSpindleKComplex","PupilLightReflex","CoughFlowBurst","DesaturationRecovery", ...
        "OJIPFluorescence","StomatalClosure","SapFlowLag","LeafNyctinasty","FungalGrowthPulse", ...
        "PianoInharmonicDecay","GuitarPluckDualDecay","BellBeating","DrumModePacket","TrafficStopGo", ...
        "ElevatorRide","ThermostatCycle","AtmosphericRiver","HeatwaveFrontBreak","DroughtRecovery", ...
        "ENSOEnvelope","BubbleLogPeriodic","IntradayVolatilityU","LiquidityDrought","YieldShockRecovery", ...
        "AnalyticNearPole","ChirpCuspCollision","LogPeriodicCusp","CancellationNeedle","RegularityQuilt"];
    
    
    Name = [category1(:); category2(:); category3(:); category4(:); category5(:); ...
            category6(:); category7(:); category8(:); category9(:); category10(:)];
    
    
    % Create Category vector: each category index repeated for number of names in that category
    catCounts = [numel(category1), numel(category2), numel(category3), numel(category4), ...
                 numel(category5), numel(category6), numel(category7), numel(category8), ...
                 numel(category9), numel(category10)];
    Category = repelem(1:10, catCounts).';
    
    % Assign RecommendedN = 1024 for each signal (one per Name entry)
    RecommendedN = repmat(1024, numel(Name), 1);
    
    % Build FunctionName as "bend1d.<ID>_<Name>" for each entry
    % sanitize Name to remove any characters that might be problematic (spaces, etc.)
    %safeNames = regexprep(Name, '\s+', '');
    %FunctionName = ID + "_" + safeNames;
    
    signalCatalog = table( ...
        ID,Name,Category,RecommendedN);
    end
    
    T = signalCatalog;
end